server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  #    instance:
  #      prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    # 下面两句不然注册中心注册到注册中心
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #设置三个地址集群高可用，互相注册。至少要求主备模式
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      # 打开注册中心:http://localhost:8761
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/