server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  #    instance:
  #      prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/