spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # default-filters:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          #http://localhost:8080/USER/user?name=a
          enabled: true
      routes:
        - id:  163
          uri: http://www.163.com/
          predicates:
            # 转发该路径
            - Path=/usera/**
          # 带前缀
          filters:
            - StripPrefix=1
        #id 必须大写，名称随便
        - id:  REGISTERCENTER
          # lb代表从注册中心获取服务，SERVER:为注册中心的服务名称
          #会用自带的负载均衡
          uri: lb://SERVER
          predicates:
            #user名称随便，但是必须大写
            - Path=/USER/**
          filters:
            - StripPrefix=1

#注意：服务中心和提供的服务都要启动
#打开链接测试，不停刷新会发现负载均衡
#http://localhost:8080/USER/user?name=a

