server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  #    instance:
  #      prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    # 下面两句不然注册中心注册到注册中心
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # 打开注册中心:http://localhost:8761/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/